export const SAVE_CITY = 'SAVE_CITY';
export const SEARCH_STATUS = 'SEARCH_STATUS';
export const FORECAST_WEATHER = 'FORECAST_WEATHER';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const FORECAST_SOME_DAYS = 'FORECAST_SOME_DAYS';
export const FORECAST_DAYS_STATUS = 'FORECAST_DAYS_STATUS';
export const SET_CUSTOM_FORECAST_WEATHER = 'SET_CUSTOM_FORECAST_WEATHER';
